### ISSUE TITLE
gorepl-mode will be enable in new opened files/buffers too

### ISSUE THREAD

**Issue by stardiviner** [manute/gorepl-mode#2]
Enable /gorepl-mode/ will be enabled in all after opened new buffers.

For example, when I enable gorepl-mode in go-mode buffer, with config:

```
(add-hook 'go-mode-hook #'gorepl-mode)
```

Then gorepl-mode will enabled in other new opened files, buffers too, weird.

I checked `find-file-hook`, and `find-file-hooks`, no `gorepl-mode` in those hooks.

**Comment by manute** [comment]
It is weird yes, I will check it 

Thanks for open the issue

**Comment by stardiviner** [comment]
After test with `emacs -q`, I found `gorepl-mode` is enabled by default.

**Comment by stardiviner** [comment]
After check out source code, I found the reason is in `(easy-menu-define gorepl-mode gorepl-mode-map` code definition.

**Comment by manute** [comment]
Why? Could you send a pull req if you are sure about that? 
Thanks

**Comment by stardiviner** [comment]
I'm sure about that, I tested it.
Ok, I will send a pull request.
