### ISSUE TITLE
Echo commands sent to gore

### ISSUE THREAD

**Issue by grettke** [manute/gorepl-mode#4]
Your mode rocks. It makes using gore easy and fun. This is my first time using and totally changes learning Go. Now, I can't figure something out:

On my box the `comint-send-string` commands are not echoed. So it is confusing to issue a command and see the results without knowing what command was run. I wonder if I need to set `comint-process-echoes` to true, but I didn't figure out where to do that yet. Are the commands echoed for you? 

I tried one of these and that didn't work for me either:
` (add-hook 'gorepl-mode-hook (lambda () (setq-local comint-process-echoes t)))`

I am probably doing something wrong. 

How do I make command sent to gore echoed?

**Comment by manute** [comment]
Hi @grettke , I'm glad you like the mode. 

I assume the mode is working good no? Emacs version? . 

Btw this mode only sends a string (or region ) https://github.com/manute/gorepl-mode/blob/master/gorepl-mode.el#L97 to gore and gore do the rest so I think if gore doesn't echoed them this mode neither.

Honestly this is my first mode for emacs so maybe I missed something for echoing it , any help would be really appreciated.

**Comment by grettke** [comment]
@manute It is working perfectly. I love it. I was just curious if I could get echo working using the comint variables. I will report back. You are right, I couldn't find gore echoing, either.

I will make a pull request this week.

**Comment by grettke** [comment]
@manute The last commit was Nov 21, 2015. The codebase is stable and well tested.

Can you tag a 1.0.0 release before I start submitting pull requests this week?

**Comment by manute** [comment]
Done . Thanks!

**Comment by grettke** [comment]
If we really wanted to see echo, it can be as simple as switching to that
buffer, inserting the text, and sent calling comint-send-input. I mean, it
is that simple, I tried it. I will start there and send you something.

Sincerely,

Grant Rettke

**Comment by manute** [comment]
sounds good  👍
